require("nvim-web-devicons").setup()
require("fidget").setup()
require("nvim-ts-autotag").setup()
require("nvim-autopairs").setup()
require("textcase").setup()
require("Comment").setup()
require("octo").setup()
require("indent_blankline").setup()
