-- vim.g.dbs = [
-- {name="local","url"=
-- 	 "mysql://root:qwe123qwe@127.0.0.1:3306/moodle",}
-- ]

-- vim.keymap.set(
-- 	"n",
-- 	"<leader>db",
-- 	"<CMD>BufferCloseAllButPinned<CR>" .. "<CMD>NvimTreeClose<CR>" .. "<CMD>DBUI<CR>",
-- 	{ noremap = false, silent = false }
-- )
